/*
 * stackvm.h — Core StackVM types and syscall ABI.
 *
 * Include this header in every program targeting the StackVM runtime.
 * It provides the fundamental integer types and the raw syscall function.
 *
 * Syscall ABI
 * -----------
 * All syscalls follow the 4-argument unsigned-64-bit convention:
 *
 *     size_t syscall(size_t sys_n, size_t a0, size_t a1, size_t a2, size_t a3);
 *
 * The return value is delivered in the slot that was occupied by a3 on the
 * stack (i.e. the caller reads the result from the variable/register used as
 * the last argument).  The compiler handles this transparently.
 *
 * syscall() is declared here as an extern; its implementation is generated by
 * the compiler as a CALL_E / BCCE_SYSCALL instruction sequence.
 */

#ifndef STACKVM_H
#define STACKVM_H

/* Fixed-width integer types */
typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;

typedef signed char int8_t;
typedef signed short int16_t;
typedef signed int int32_t;
typedef signed long long int64_t;

typedef uint64_t size_t;
typedef int64_t ssize_t;
typedef uint64_t uintptr_t;
typedef int64_t ptrdiff_t;

/* NULL pointer constant */
#ifndef NULL
#define NULL ((void *)0)
#endif

/*
 * Raw syscall — invoked by the CALL_E / BCCE_SYSCALL mechanism.
 * Do NOT call this directly; use the typed wrappers in the appropriate
 * stackvm_*.h header instead.
 */
extern size_t syscall(size_t sys_n, size_t a0, size_t a1, size_t a2, size_t a3);

#endif /* STACKVM_H */
